In [1]:
import numpy as np

In [3]:
a = np.array([[1,1],
            [0,1]])
b = np.arange(4).reshape((2,2))

In [4]:
c = a*b
c_dot = np.dot(a,b)

In [5]:
print(c)
print(c_do)#矩阵乘法

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [11]:
d = np.random.random((2,4))
print(d)
print(np.sum(d,axis=1))#axi=0是列，axis=1是行
print(np.min(d,axis=0))
print(np.max(d))

[[ 0.6249169   0.65724308  0.95880385  0.65105475]
 [ 0.72734332  0.9905196   0.42527533  0.66334559]]
[ 2.89201858  2.80648383]
[ 0.6249169   0.65724308  0.42527533  0.65105475]
0.990519598781


In [17]:
A = np.arange(2,14).reshape((3,4))
print(np.argmin(A))
print(np.argmax(A))#加arg是加索引，要其索引位置
print(np.mean(A))
print(np.average(A))
print(np.median(A))
print(np.cumsum(A))#累加
print(np.nonzero(A))#非零的是哪些

0
11
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [24]:
B = np.arange(14,2,-1).reshape((3,4))#从14到2步长是-1
print(B)
print(np.sort(B))#逐行排序
print(np.transpose(B))
print(B.T)
print(np.clip(B,5,9))
print(np.mean(A,axis=1))
print(np.mean(A,axis=0))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
[  3.5   7.5  11.5]
[ 6.  7.  8.  9.]
