In [1]:
import numpy as np

In [5]:
A = np.array([1,1,1])
B = np.array([2,2,2])
#A = np.array([1,1,1])[:,np.newaxis]还可以这么写
#B = np.array([2,2,2])[:,np.newaxis]
print(np.vstack((A,B)))#vertical stack

[[1 1 1]
 [2 2 2]]


In [8]:
C = np.vstack((A,B))
D = np.hstack((A,B))#horizonal stack
print(D)
print(A.shape,D.shape)

[1 1 1 2 2 2]
(3,) (6,)


In [12]:
print(A[np.newaxis,:])#行加了一个维度
print(A[:,np.newaxis].shape)#列加了一个维度

[[1 1 1]]
(3, 1)


In [13]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print(A)
print(B)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


In [16]:
C = np.concatenate((A,B,B,A),axis=1)#连接的形式
print(C)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
