In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
b=a #判断b是不是a
b is a

True

In [5]:
b[1:3]=[22,33]
a

array([ 0, 22, 33,  3])

In [6]:
b = a.copy()#利用copy可以不关联
b


array([ 0, 22, 33,  3])

In [7]:
a[2] = 11111
b

array([ 0, 22, 33,  3])

In [8]:
a

array([    0,    22, 11111,     3])