In [1]:
import numpy as np

In [4]:
array = np.array([[1,2,3],[2,3,4]])

In [5]:
print(array)
print('number of dim:',array.ndim )
print('shape',array.shape)
print('size ',array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape (2, 3)
size  6


In [6]:
a = np.array([11,22,33,44])
b = np.arange(4)

In [7]:
print(a,b)
c = a-b

[11 22 33 44] [0 1 2 3]


In [8]:
print(c)

[11 21 31 41]


In [9]:
d = b**2
print(d)

[0 1 4 9]


In [10]:
e = np.sin(a)
print(e)

[-0.99999021 -0.00885131  0.99991186  0.01770193]


In [11]:
print(b<3)

[ True  True  True False]
