In [1]:
import numpy as np

In [10]:
A = np.arange(3,15).reshape((3,4))
print(A)
print(A[2,1])#等于print(A[2],[1])
print(A[2,:])
print(A[:,1])



[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
12
[11 12 13 14]
[ 4  8 12]


In [11]:
for row in A:#迭代行
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [12]:
for column in A.T:#利用转置，迭代列，因为没有直接迭代列的啊
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [14]:
print(A.flatten())#这是说拍平了的啊

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
for item in A.flat:#单个数字迭代
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14
